[workspace]
resolver = "2"
members = [
    "chess_rot_engine",
    "chess_rot_ui"
]

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[profile.release]
overflow-checks = false
