[package]
name = "chess_rot_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
chess_rot_engine = {version = "*", path = "../chess_rot_engine"}
eframe = { version = "*"}
egui_extras = { version = "*", features = ["default", "image"] }
env_logger = "0.11.6"


